### ISSUE TITLE
Deploy fails but the GitHub Action continues to run in a loop

### ISSUE THREAD

**Issue by mrljsh** [digitalocean/app_action#113]
When my  App Platform deployment fails, the GitHub Action does not stop and continues to run in a loop, effectively doing nothing. This issue causes unnecessary usage of resources and potential delays in identifying and resolving the root cause of the failure.

**Comment by andreieuganox** [comment]
+1
This bug is here forever...

**Comment by r0b0tt** [comment]
Is there any update on this?

**Comment by markusthoemmes** [comment]
We've just released v2.0.0 of the app which is supposed to fix this: https://github.com/digitalocean/app_action/discussions/122. Please let us know if you're still encountering this issue!
