### ISSUE TITLE
Secret env variables

### ISSUE THREAD

**Issue by NexPB** [digitalocean/app_action#140]
The [README](https://github.com/digitalocean/app_action/blob/main/README.md) mentions the following: "The in-filesystem app spec can also be templated with environment variables automatically (see examples below)." but I can't seem to find the examples, I have feeling the "examples" is what I would want to do.

My goal is getting secrets within the app spec file, without having them visible in the commit history.

**Comment by markusthoemmes** [comment]
@NexPB Thanks for the report! I've sent a PR adding an example to the README. Please see if that answers the question for you and if not, feel free to comment on the PR as well. Thanks!
