### ISSUE TITLE
Add Real-Time Log Display in GitHub Actions Console

### ISSUE THREAD

**Issue by RafaelScharf** [digitalocean/app_action#73]
Currently, I am using the GitHub Action provided by Digital Ocean to deploy my application. However, I noticed that unlike the Digital Ocean panel, GitHub Actions doesn't display real-time logs during the deployment. This makes it challenging to track the progress of the deployment and identify any potential issues that may arise during the process.

![image](https://github.com/digitalocean/app_action/assets/42837920/54b5cbba-7935-41d8-b967-9bc29d63d82c)

**Request:**
I would like to request the addition of a feature that allows displaying real-time logs directly in the GitHub Actions console. This would make the deployment process more transparent and efficient, enabling easier identification and resolution of any issues that may occur.

**Benefits:**

1. Improved Visibility: Displaying real-time logs in the GitHub Actions console would provide a clear view of the deployment status, allowing developers to track progress more efficiently.

2. Quick Diagnostics: With the ability to instantly view logs, it would be easier to identify potential errors or failures during the deployment process, enabling immediate correction.

3. Enhanced Continuous Integration: By showing real-time logs, continuous integration would be more effective as developers would have precise information about each step of the process.

**Comment by markusthoemmes** [comment]
We've just released v2.0.0 of the action which optionally prints the build and/or deployment logs after the deployment and also surfaces those in an action output for you to use in subsequent steps. It's not real-time for now, but it should fulfill the described goal. Please check it out: https://github.com/digitalocean/app_action/discussions/122.
