### ISSUE TITLE
Feature Request:  Save meta data about the deployment in an artifact

### ISSUE THREAD

**Issue by on3al** [digitalocean/app_action#92]
It would be extremely useful if this deployment action would save details about the deploy in an artifact that could be read by a subsequent job.

The use case would be, once the deployment succeeds, I have a job that runs afterwards that runs a set of playwright end to end tests against the fresh deployment.  If any of those tests fail I want to roll back to the previous deployment.

It would be great if the artifact was either a json file or something easy to consume in the github action that contained the deployment_id and maybe even just the straight up doctl command or curl request to run to rollback the deploy.

**Comment by markusthoemmes** [comment]
We've just released v2.0.0 of the app which surfaces the entire app state after the deployment. That should allow you to make sense of things as described. Please check it out: https://github.com/digitalocean/app_action/discussions/122.
